version: "3.9"
services:
  app:
    image: petclinic:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - spring_profiles_active=mysql            # Use mysql profile in spring-boot
      - MYSQL_URL=jdbc:mysql://mysql/petclinic  # We only need to override the connection url.
                                                # All other settings are using working defaults.
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "mysql_conf:/etc/mysql/conf.d"
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_conf:
  mysql_data: